theme: jekyll-theme-cayman
# show_edit_on_github: false
# github:
#   is_project_page: false
github:
  zip_url: https://github.com/x6zeng/NLP-Active-Learning-Pipeline
  another_url: https://www.google.com/
title: Active learning for NLP in predicting the relevance and sentiment of tweets about politics of China
description: Authors - Yunyi Huang, Xiaotong Zeng
